/**
 * Authentication models for json-server-auth integration.
 *
 * These interfaces define the data structures used for authentication
 * operations (login, register) compatible with json-server-auth.
 *
 * @category Models
 * @see https://github.com/jeremyben/json-server-auth
 */

/**
 * Represents a user in the system.
 *
 * The `id` field is optional because it's not present when creating a new user
 * (json-server-auth generates it automatically).
 *
 * @category Models
 */
export interface User {
  /**
   * Unique identifier (generated by json-server-auth)
   * @optional - Absent at user creation
   */
  id?: number;

  /**
   * User email address
   * @required
   */
  email: string;
}

/**
 * Request payload for user login.
 *
 * Used when authenticating an existing user with json-server-auth.
 *
 * @category Models
 * @see AuthResponse
 */
export interface LoginRequest {
  /**
   * User email address
   * @required
   */
  email: string;

  /**
   * User password (plain text, will be hashed by json-server-auth)
   * @required
   */
  password: string;
}

/**
 * Request payload for user registration.
 *
 * Used when creating a new user account with json-server-auth.
 *
 * @category Models
 * @see AuthResponse
 */
export interface RegisterRequest {
  /**
   * User email address
   * @required
   */
  email: string;

  /**
   * User password (plain text, will be hashed by json-server-auth)
   * @required
   */
  password: string;
}

/**
 * Response payload from authentication operations.
 *
 * Returned by json-server-auth after successful login or registration.
 *
 * @category Models
 * @see LoginRequest
 * @see RegisterRequest
 */
export interface AuthResponse {
  /**
   * JWT access token for authenticated requests
   * @required
   */
  accessToken: string;

  /**
   * Authenticated user data
   * @required
   */
  user: User;
}
