/**
 * Order models for the CRM system.
 *
 * Orders are the central entity of the CRM. Total amounts (totalHt, totalTtc)
 * are calculated on the frontend before sending to the API.
 *
 * @category Models
 */

/**
 * Represents an order in the CRM system.
 *
 * Orders contain customer information, project details (days, daily rate),
 * tax information, and calculated totals.
 *
 * @category Models
 */
export interface Order {
  /**
   * Unique identifier (auto-generated by json-server)
   * @required
   */
  id: number;

  /**
   * Customer name or company name
   * @required
   */
  customer: string;

  /**
   * Number of days for the project
   * @required
   * @minimum 1
   */
  nbDays: number;

  /**
   * Daily rate (TJM - Taux Journalier Moyen) in euros
   * @required
   * @minimum 0
   */
  tjm: number;

  /**
   * VAT rate in percentage (e.g., 20 for 20%)
   * @required
   * @minimum 0
   * @maximum 100
   */
  tauxTva: number;

  /**
   * Total amount excluding VAT (HT - Hors Taxes)
   * Calculated as: nbDays * tjm
   * @required
   * @readonly - Calculated automatically on frontend
   */
  totalHt: number;

  /**
   * Total amount including VAT (TTC - Toutes Taxes Comprises)
   * Calculated as: totalHt * (1 + tauxTva / 100)
   * @required
   * @readonly - Calculated automatically on frontend
   */
  totalTtc: number;
}

/**
 * Payload for creating a new order.
 *
 * Excludes `id` (generated by json-server) and calculated totals
 * (`totalHt`, `totalTtc`) which are computed on the frontend before sending.
 *
 * @category Models
 * @see Order
 */
export type CreateOrder = Omit<Order, 'id' | 'totalHt' | 'totalTtc'>;

/**
 * Payload for updating an existing order.
 *
 * Excludes calculated totals (`totalHt`, `totalTtc`) which are computed
 * on the frontend before sending. The `id` is required to identify the order.
 *
 * @category Models
 * @see Order
 */
export type UpdateOrder = Omit<Order, 'totalHt' | 'totalTtc'>;

